language: php
php:
    - '5.6'
    - '7.0'
    - '7.1'
    - hhvm
    - nightly
before_script:
    - composer self-update
    - composer update --no-interaction --prefer-lowest
    - composer dumpautoload -o
script:
    - composer validate --strict
    - vendor/bin/phpcs --standard=psr2 src/
    - vendor/bin/phpunit
after_success:
  - bash <(curl -s https://codecov.io/bash)